version: '3'
services:
  edit-db:
    build: .
    image: sogis/postgis-db:localbuild
    environment:
      PG_DATABASE: edit
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
    ports:
      - "54321:5432"
    volumes:
      - ./development_dbs/setup.sql:/pgconf/setup.sql
      - sshd_edit:/sshd:delegated
      - pgconf_edit:/pgconf:delegated
      - pgdata_edit:/pgdata:delegated
      - pgwal_edit:/pgwal:delegated
      - recover_edit:/recover:delegated
      - backrestrepo_edit:/backrestrepo:delegated
    hostname: primary-edit
  pub-db:
    build: .
    image: sogis/postgis-db:localbuild
    environment:
      PG_DATABASE: pub
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
    ports:
      - "54322:5432"
    volumes:
      - ./development_dbs/setup.sql:/pgconf/setup.sql
      - sshd_pub:/sshd:delegated
      - pgconf_pub:/pgconf:delegated
      - pgdata_pub:/pgdata:delegated
      - pgwal_pub:/pgwal:delegated
      - recover_pub:/recover:delegated
      - backrestrepo_pub:/backrestrepo:delegated
    hostname: primary-pub
volumes:
  sshd_edit:
  pgconf_edit:
  pgdata_edit:
  pgwal_edit:
  recover_edit:
  backrestrepo_edit:
  sshd_pub:
  pgconf_pub:
  pgdata_pub:
  pgwal_pub:
  recover_pub:
  backrestrepo_pub:
